### ISSUE TITLE
Code availability update

### ISSUE THREAD

**Issue by bc** [elliottwu/unsup3d#1]
Hi! I would love to try this out and see what I can adapt it into. When do you target releasing the code?

**Comment by elliottwu** [comment]
Hi! Sorry for the delay! The initial version is now released.

**Comment by bc** [comment]
Awesome thank you! I'm installing it now on my mac through docker. Roughly, what was the amount of computation time it took per frame of input on the pretrained model?

**Comment by elliottwu** [comment]
The inference is realtime (25+fps) on CPU. The neural_renderer does not have CPU implementation, so the training/testing code will require GPU. I plan to release some demo code without using the neural_renderer in a few days, which will be able to run on CPU.
