### ISSUE TITLE
Download Pretrained Models

### ISSUE THREAD

**Issue by Nancyhhh** [elliottwu/unsup3d#11]
Congratulations!
I am so interested in your project. When i was running the .sh file to download the pretrained models, i always get the network problem. It is so nice of you if you could send your all pretrained models to my e-mail box. Best wishes to you! Have a nice day! Here is my address : CYNh_e@126.com.

**Comment by elliottwu** [comment]
Hi! 
Thanks! Can you try these links? 
pretrained models: [cat](https://unioxfordnexus-my.sharepoint.com/:u:/g/personal/sann6319_ox_ac_uk/EUfNTnR8g2JGtvFVY99OeQUB1N4Zm7Fvi71ovGjKwdr99Q?download=1), [celeba](https://unioxfordnexus-my.sharepoint.com/:u:/g/personal/sann6319_ox_ac_uk/EeqxFjn7kA9Ms4a6VrrPliIBCLQZS-EnwvbSu4Iy181eZQ?download=1), [synthetic face](https://unioxfordnexus-my.sharepoint.com/:u:/g/personal/sann6319_ox_ac_uk/EWNJX1RXm5lBiZ2KxDthI40BwgJRKDdxwZxxQLT-0t0_8w?download=1)

**Comment by Nancyhhh** [comment]
Ok, I will try it! Thank you very much! Best wishes!
