### ISSUE TITLE
How to test unsup3d on Google Colab?

### ISSUE THREAD

**Issue by Salix-y** [elliottwu/unsup3d#27]
Hi, when I tried to  test unsup3d on Google Colab, I had some problems, such as:

/usr/local/bin/python: Error while finding module specification for 'demo.demo' (AttributeError: module 'demo' has no attribute '__path__')

so, how to write a Colab notebook can successfully test unsup3d?
just like: https://blog.csdn.net/yrwang_xd/article/details/103150691 

Thanks!

**Comment by Salix-y** [comment]
thanks! This problem has been solved！

**Comment by molo32** [comment]
hello, you can share your colab notebook.
