### ISSUE TITLE
Forbidden Error for Syncar dataset. 

### ISSUE THREAD

**Issue by terrybelinda** [elliottwu/unsup3d#35]
Hello, 
Thank you for sharing your amazing work. We are students trying to replicate this on the car dataset. Unfortunately, it seems like there are some permission issues to download the data. 

`curl -o syncar.zip "https://www.robots.ox.ac.uk/~vgg/research/unsup3d/data/syncar.zip" `

does not work because of a 403 error ( Permission denied ).
Would it be possible to grant access for the same as the others seems to be working fine ?

**Comment by elliottwu** [comment]
Hi thanks for the notice! That was a permission issue. It should be fixed now!

**Comment by terrybelinda** [comment]
Thank you for the access!
